<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="KishoreRamya" failures="1" tests="6" name="Test" time="200.164" errors="0" timestamp="2025-04-16T15:20:34 IST">
  <testcase classname="testCases.TC003_LoginTest_DataDrivenTesting" name="verify_login" time="1.646"/>
  <testcase classname="testCases.TC003_LoginTest_DataDrivenTesting" name="verify_login" time="1.966"/>
  <testcase classname="testCases.TC003_LoginTest_DataDrivenTesting" name="verify_login" time="61.198">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC003_LoginTest_DataDrivenTesting.verify_login(TC003_LoginTest_DataDrivenTesting.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_login -->
  <testcase classname="testCases.TC003_LoginTest_DataDrivenTesting" name="verify_login" time="61.273"/>
  <testcase classname="testCases.TC003_LoginTest_DataDrivenTesting" name="verify_login" time="1.896"/>
  <testcase classname="testCases.TC003_LoginTest_DataDrivenTesting" name="verify_login" time="61.491"/>
</testsuite> <!-- Test -->
